import type { NextPage } from "next";

import NavigationBar from "../../components/Navigation";
import AmountCard from "../../components/buyLoka/AmountCard";
import DurationCard from "../../components/buyLoka/DurationCard";
import ReviewCard from "../../components/buyLoka/ReviewCard";
import SimulationCard from "../../components/buyLoka/SimulationCard";
import DashboardMenu from "../../components/DashboardMenu";
import Footer from "../../components/Footer";
import Head from "next/head";

const BuyLoka: NextPage = () => {
  return (
    <div className="bg-btc-pattern">
      <Head>
        <title>Loka </title>
        <meta
          content="Mint Loka Mining Contract"
          name="int Loka Mining Contract"
        />
        <link href="/favico_loka.png" rel="icon" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@300;500&display=swap"
          rel="stylesheet"
        />
      </Head>
      {/* Navigation */}
      <nav className="w-full h-20 sm:h-16 bg-custom-blue">
        {/* Navigation content */}
        <NavigationBar />
      </nav>

      {/* Buy Loka */}
      <div className="flex-grow flex flex-col md:flex-row h-full w-full  mx-auto">
        <div className="hidden lg:flex h-full">
          <DashboardMenu />
        </div>
        <div className="flex-grow flex flex-col md:flex-row lg:max-w-[80%] mx-auto ">
          <div className="w-full flex-grow flex flex-col ">
            <section className="p-5 pt-10 pb-0 lg:flex justify-start text-3xl text-center  lg:text-left text-white">
              BUY LOKA
            </section>
            <div className="flex-grow flex flex-col md:flex-row h-full w-full justify-start items-start text-left  mx-auto">
              <div className=" lg:max-w-[50%] w-full mx-auto justify-start items-start text-center lg:text-left ">
                <section className="p-0 lg:flex border-b-[1px] border-[#8293aa]">
                  <AmountCard />
                </section>
                <section className="p-0 lg:flex border-b-[1px] border-[#8293aa]">
                  <DurationCard />
                </section>
                <section className="p-0 lg:flex">
                  <SimulationCard />
                </section>
              </div>
              <div className="sticky-div lg:max-w-[50%] w-full mx-auto  justify-start items-start lg:text-left text-center">
                <section className="p-0 lg:flex ">
                  <ReviewCard />
                </section>
              </div>
            </div>
            <section className=" p-10">{/*transaction*/}</section>
          </div>
        </div>
      </div>

      <footer className="w-full">
        <Footer />
      </footer>
    </div>
  );
};

/* return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <HeroSection></HeroSection>
        <h1 className={styles.title}>
          Welcome to <a href="">RainbowKit</a> + <a href="">wagmi</a> +{" "}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://rainbowkit.com">
            <h2>RainbowKit Documentation &rarr;</h2>
            <p>Learn how to customize your wallet connection flow.</p>
          </a>

          <a className={styles.card} href="https://wagmi.sh">
            <h2>wagmi Documentation &rarr;</h2>
            <p>Learn how to interact with Ethereum.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/rainbow-me/rainbowkit/tree/main/examples"
          >
            <h2>RainbowKit Examples &rarr;</h2>
            <p>Discover boilerplate example RainbowKit projects.</p>
          </a>

          <a className={styles.card} href="https://nextjs.org/docs">
            <h2>Next.js Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a
            className={styles.card}
            href="https://github.com/vercel/next.js/tree/canary/examples"
          >
            <h2>Next.js Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            className={styles.card}
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};*/

export default BuyLoka;
